openapi: 3.1.0
info:
  version: 1.0.0
  title: Spring Boot 3 - Api First Engineering
  termsOfService: https://www.jesusfc.com/terms-of-service
  contact:
    name: Jesús Fdez. Caraballo
    email: jesus.fdez.caraballo@gmail.com
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
  description: Best Practices to Develop First Class APIs

servers:
  - url: http://localhost:8080/api
    description: Localhost server

paths:
  /example:
    get:
      summary: Get example data
      description: Retrieve example data from the server.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string