openapi: 3.1.0
info:
  version: 1.0.0
  title: Spring Boot 3 - Api First Engineering
  termsOfService: https://www.jesusfc.com/terms-of-service
  contact:
    name: Jesús Fdez. Caraballo
    email: jesus.fdez.caraballo@gmail.com
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
  description: Best Practices to Develop First Class APIs
security:
  - batch_auth: [ ]
tags:
  - name: Customer
    description: Customer related endpoints
  - name: User
    description: User related endpoints
  - name: Products
    description: Product operations
servers:
  - url: http://localhost:8080/api
    description: Localhost server
paths:
  /v1/customers:
    $ref: paths/v1/customers.yaml
  /v1/customers/{customer_id}:
    $ref: paths/v1/customers_{customer_id}.yaml
  /v1/products:
    $ref: paths/v1/products.yaml
  /v1/products/{productId}:
    $ref: paths/v1/products_{productId}.yaml
  /v1/orders:
    $ref: paths/v1/orders.yaml
  /v1/orders/{orderId}:
    $ref: paths/v1/orders_{orderId}.yaml
  /v1/categories:
    $ref: paths/v1/categories.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic